export { default as GlobalStyle } from './GlobalStyle'
export { default as MainContentContainer } from './MainContentContainer'
export { default as HeaderContainer } from './HeaderContainer'
export { default as TopTriangle } from './TopTriangle'
export { default as DescriptionContainer } from './DescriptionContainer'
export { default as SectionContainer } from './SectionContainer'
export { ProjectDescription, ProjectImage } from './ProjectStyles'
